// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROBOSEARCH;

import javax.vecmath.Vector3d;

/************************************************************/
/**
 * 
 */
public interface AdapterInterface {
	/**
	 * 
	 * @return 
	 * @param coorX 
	 * @param coorY 
	 */
	//Detailed information about this function is in Adapter.java
	//Since this is only interface no implementations have been made!
	public Vector3d convertCoordinate(double coorX, double coorY);
};
