// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROBOSEARCH;

/************************************************************/
/**
 * 
 */
public enum AvailableCommands {
	/**
	 * 
	 */
	START_CONTROL,
	/**
	 * 
	 */
	STOP_CONTROL,
	/**
	 * 
	 */
	GO_DESTINATION,
	/**
	 * 
	 */
	GO_UP,
	/**
	 * 
	 */
	GO_RIGHT,
	/**
	 * 
	 */
	GO_DOWN,
	/**
	 * 
	 */
	GO_LEFT,
	/**
	 * 
	 */
	STOP_MISSION;
	
};
