// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROBOSEARCH;

import RootElement.ROBOSEARCH.AvailableCommands;

/************************************************************/
/**
 * 
 */
public class Command {
	/**
	 * 
	 */
	private AvailableCommands command;

	/**
	 * 
	 * @param command 
	 */
	//This function is used by central station to send commands
	//to robots from AvailableCommands enumeration. it will be  
	//executed in robots class. Also the implementations are in Robot.java
	//because command is used as message object how it will be executed
	//should be in the class that will be affected.
	//in order to add more commend types the enumeration should be added
	//also the implementation should be in robot.java!!
	public Command(AvailableCommands command) {
		this.command = command;
	}
	public AvailableCommands getCommand() {
		return this.command;
	}
};
