// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROBOSEARCH;

/************************************************************/
/**
 * 
 */
public enum CoordinateStatus {
	/**
	 * 
	 */
	VISITED,
	/**
	 * 
	 */
	EMPTY,
	/**
	 * 
	 */
	OBSTACLE;
};
