// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROBOSEARCH;

/************************************************************/
/**
 * 
 */
public interface Observer {
	/**
	 * 
	 */
	public Subject subject = null;

	/**
	 * 
	 * @return 
	 */
	public void update(Command command);
};
