// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROBOSEARCH;

/************************************************************/
/**
 * 
 */
public enum RobotStatus {
	/**
	 * 
	 */
	BUSY,
	/**
	 * 
	 */
	MALFUNCTION,
	/**
	 * 
	 */
	RUNNING,
	/**
	 * 
	 */
	AVAILABLE,
	/**
	 * 
	 */
	DISABLED;
};
